[package]
name = "blink"
version = "0.1.0"
authors = ["Rijk van Putten <rijk@rijkvp.nl>"]
edition = "2021"
description = "Minimal break notifier"

[dependencies]
rdev = "0.5"
rodio = { version = "0.15", default-features = false, features = ["vorbis"] }
notify-rust = "4.5"
clap = { version = "3.1", features = ["derive"] }
serde = "1.0"
toml = "0.5"

[profile.release]
lto = true
strip = true
codegen-units = 1
opt-level = "z"
panic = "abort"
