name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  debug:
      runs-on: ubuntu-latest
      if: "!contains(github.event.head_commit.message, 'ci skip')"
      steps:
      - uses: actions/checkout@v2
      
      - name: Install dependenciecs (debug)
        run: sudo apt install --no-install-recommends -y libasound2-dev xorg-dev
      
      - name: Install Rust 
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-unknown-linux-gnu
          toolchain: stable
          profile: minimal
          
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose
      
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
