name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  debug:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      
      - name: Install dependenciecs (debug)
        run: sudo apt install --no-install-recommends -y libasound2-dev xorg-dev
      
      - name: Install Rust 
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-unknown-linux-gnu
          toolchain: stable
          profile: minimal
          
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose
      
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
      
  release-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependenciecs (release)
      run: sudo apt install --no-install-recommends -y libasound2-dev xorg-dev upx-ucl
    
    - name: Install Rust nightly 
      uses: actions-rs/toolchain@v1
      with:
        target: x86_64-unknown-linux-gnu
        toolchain: nightly
        profile: minimal
        components: rust-src
        override: true

    - name: Release build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target x86_64-unknown-linux-gnu --release --verbose
    
    - name: Compress binary
      run: upx --best --lzma ${{ github.action_path }}/target/release/blink
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: blink_linux-x86_64-gnu
        path: target/release/blink
